Brandon416Jr/PiChill

src/main/java/com/pichill/forum/Forum.java
=> add Forum Bean

src/main/java/com/pichill/back/Test.java
=> vincent branch first commit test

src/main/java/com/pichill/generaluser/GeneralUser.java
=> add GeneralUser Bean

src/main/java/com/pichill/owneruser/OwnerUser.java, src/main/java/com/pichill/owneruser/package-info.java
=> commit ownerUser

src/main/java/com/pichill/back/Test2.java
=> test 2 push

pom.xml
=> push update pom.xml

.gitignore, src/main/java/com/pichill/back/Test.java, src/main/java/com/pichill/back/Test2.java, src/main/java/com/pichill/backAuthority/BackAuthority.java, src/main/java/com/pichill/backAuthority/BackAuthorityDAO.java, src/main/java/com/pichill/backAuthority/BackAuthorityDAOImpl.java, src/main/java/com/pichill/backAuthority/BackAuthorityTest.java, src/main/java/com/pichill/backAuthority/Util.java, src/main/java/com/pichill/backFunction/BackFunction.java, src/main/java/com/pichill/backFunction/BackFunctionDAO.java, src/main/java/com/pichill/backFunction/BackFunctionDAOImpl.java, src/main/java/com/pichill/backFunction/BackFunctionTest.java, src/main/java/com/pichill/backFunction/Util.java, src/main/java/com/pichill/manage/Manage.java, src/main/java/com/pichill/manage/ManageDAO.java, src/main/java/com/pichill/manage/ManageDAOImpl.java, src/main/java/com/pichill/manage/ManageTest.java, src/main/java/com/pichill/manage/Util.java, src/main/resources/hibernate.cfg.xml
=> push my all updates

src/main/java/com/pichill/backauthority/BackAuthority.java, src/main/java/com/pichill/backauthority/BackAuthorityDAO.java, src/main/java/com/pichill/backauthority/BackAuthorityDAOImpl.java, src/main/java/com/pichill/backauthority/BackAuthorityTest.java, src/main/java/com/pichill/backauthority/Util.java, src/main/java/com/pichill/backfunction/BackFunction.java, src/main/java/com/pichill/backfunction/BackFunctionDAO.java, src/main/java/com/pichill/backfunction/BackFunctionDAOImpl.java, src/main/java/com/pichill/backfunction/BackFunctionTest.java, src/main/java/com/pichill/backfunction/Util.java, src/main/java/com/pichill/manage/controller/ManageServlet.java, src/main/java/com/pichill/manage/service/ManageService.java
=> service update

src/main/java/com/pichill/comment/Comment.java, src/main/java/com/pichill/comment/CommentDAO.java, src/main/java/com/pichill/comment/CommentDAOImpl.java, src/main/java/com/pichill/comment/CommentHibernate.java, src/main/java/com/pichill/comment/CommentTest.java, src/main/java/com/pichill/comment/Util.java, src/main/java/com/pichill/forumpic/ForumPic.java, src/main/java/com/pichill/forumpic/ForumPicDAO.java, src/main/java/com/pichill/forumpic/ForumPicDAOImpl.java, src/main/java/com/pichill/forumpic/ForumPicHibernate.java, src/main/java/com/pichill/forumpic/ForumTest.java, src/main/java/com/pichill/forumpic/Util.java, src/main/java/com/pichill/like/Like.java, src/main/java/com/pichill/like/LikeDAO.java, src/main/java/com/pichill/like/LikeDAOImpl.java, src/main/java/com/pichill/like/LikeHibernate.java, src/main/java/com/pichill/like/LikeTest.java, src/main/java/com/pichill/like/Util.java, src/main/java/com/pichill/post/Post.java, src/main/java/com/pichill/post/PostDAO.java, src/main/java/com/pichill/post/PostDAOImpl.java, src/main/java/com/pichill/post/PostHibernate.java, src/main/java/com/pichill/post/PostTest.java, src/main/java/com/pichill/post/Util.java, src/main/java/com/pichill/report/Report.java, src/main/java/com/pichill/report/ReportDAO.java, src/main/java/com/pichill/report/ReportDAOImpl.java, src/main/java/com/pichill/report/ReportHibernate.java, src/main/java/com/pichill/report/ReportTest.java, src/main/java/com/pichill/report/Util.java
=> 論壇5個package

src/main/java/com/pichill/cart/Cart.java, src/main/java/com/pichill/cart/CartDAO.java, src/main/java/com/pichill/cart/CartDAOImpl.java, src/main/java/com/pichill/cart/TestCart.java, src/main/java/com/pichill/cart/Util.java, src/main/java/com/pichill/generaluser/GeneralUser.java, src/main/java/com/pichill/generaluser/GeneralUserDAO.java, src/main/java/com/pichill/generaluser/GeneralUserDAOImpl.java, src/main/java/com/pichill/generaluser/TestGeneralUser.java, src/main/java/com/pichill/generaluser/Util.java, src/main/java/com/pichill/reserveorder/ReserveOrder.java, src/main/java/com/pichill/reserveorder/ReserveOrderDAO.java, src/main/java/com/pichill/reserveorder/ReserveOrderDAOImpl.java, src/main/java/com/pichill/reserveorder/TestReserveOrder.java, src/main/java/com/pichill/reserveorder/Util.java
=> Huangyininig

src/main/java/com/pichill/manage/entity/ManageTest.java, src/main/java/com/pichill/manage/model/ManageDAOImpl.java, src/main/java/com/pichill/managejdbc/Util.java, src/main/java/com/pichill/managejdbc/controller/ManageServlet.java, src/main/java/com/pichill/managejdbc/entity/Manage.java, src/main/java/com/pichill/managejdbc/entity/ManageTest.java, src/main/java/com/pichill/managejdbc/model/ManageDAO.java, src/main/java/com/pichill/managejdbc/model/ManageDAOImpl.java, src/main/java/com/pichill/managejdbc/service/ManageService.java, src/main/webapp/manage/addEmp.jsp, src/main/webapp/manage/listAllEmp.jsp, src/main/webapp/manage/listAllManage.jsp, src/main/webapp/manage/listOneEmp.jsp, src/main/webapp/manage/listOneManage.jsp, src/main/webapp/manage/select_page.jsp, src/main/webapp/manage/update_emp_input.jsp, src/main/webapp/manage/update_manage_input.jsp
=> update JDBCDAO & HibernateDAO excluded servlet.java, service.java and

src/main/java/com/pichill/contactus/Util.java, src/main/java/com/pichill/contactus/controller/ContactUsServlet.java, src/main/java/com/pichill/contactus/entity/ContactUs.java, src/main/java/com/pichill/contactus/entity/TestContactUs.java, src/main/java/com/pichill/contactus/model/ContactUsDAO.java, src/main/java/com/pichill/contactus/model/ContactUsDAOImpl.java, src/main/java/com/pichill/contactus/service/ContactUsService.java, src/main/java/com/pichill/court/Court.java, src/main/java/com/pichill/court/CourtDAO.java, src/main/java/com/pichill/court/CourtDAOImpl.java, src/main/java/com/pichill/court/TestCourt.java, src/main/java/com/pichill/court/Util.java, src/main/java/com/pichill/owneruser/OwnerUser.java, src/main/java/com/pichill/owneruser/OwnerUserDAO.java, src/main/java/com/pichill/owneruser/OwnerUserDAOImpl.java, src/main/java/com/pichill/owneruser/TestOwnerUser.java, src/main/java/com/pichill/owneruser/Util.java, src/main/java/com/pichill/place/Place.java, src/main/java/com/pichill/place/PlaceDAO.java, src/main/java/com/pichill/place/PlaceDAOImpl.java, src/main/java/com/pichill/place/TestPlace.java, src/main/java/com/pichill/place/Util.java
更新ownerUser，移除無用的引用
上傳contactus所有
上傳所有Util
=> Yi yun wang

src/main/java/com/pichill/contactus/entity/ContactUs.java, src/main/java/com/pichill/contactus/entity/ContactUsHibernate.java, src/main/java/com/pichill/contactus/model/ContactUsDAO.java, src/main/java/com/pichill/court/Court.java, src/main/java/com/pichill/court/CourtDAOImpl.java, src/main/java/com/pichill/court/CourtHibernate.java, src/main/java/com/pichill/owneruser/OwnerUser.java, src/main/java/com/pichill/owneruser/OwnerUserDAOImpl.java, src/main/java/com/pichill/owneruser/OwnerUserHibernate.java, src/main/java/com/pichill/place/Place.java, src/main/java/com/pichill/place/PlaceDAOImpl.java, src/main/java/com/pichill/place/PlaceHibernate.java
=> 企業會員、場地、球館、聯絡我們更新

src/main/java/com/pichill/owneruser/OwnerUser.java, src/main/java/com/pichill/owneruser/OwnerUserDAOImpl.java, src/main/java/com/pichill/owneruser/OwnerUserHibernate.java, src/main/java/com/pichill/owneruser/TestOwnerUser.java
刪除oLstLogTime、oRegisterDate@Column 新增 updatable = false、oRegisteTime改成oRegisteDate
=> 刪除oLstLogTime、oRegisterDate @Column 新增updatable=false、oRegisteTime改

src/main/java/com/pichill/contactus/entity/ContactUs.java, src/main/java/com/pichill/court/Court.java, src/main/java/com/pichill/owneruser/entity/OwnerUser.java, src/main/java/com/pichill/owneruser/model/OwnerUserDAO.java, src/main/java/com/pichill/place/Place.java
ownerUser [oBirth, oIDNum, oGender] => updatable = "false"
contactUs [formTime] => insertable = "false", updatable = "false" contactUs [formType, formPurpose, formContent, formPic, gUserID, oUserID] => updatable = "false"
court [courtApplyTime] => insertable = "false", updatable = "false" court [courtOnTime] => updatable = "false"
place [courtID] => updatable = "false"
=> 部分內容新增 insertable = "false", updatable = "false"

src/main/java/com/pichill/post/controller/PostServlet2.java, src/main/java/com/pichill/post/model/PostDAO.java, src/main/java/com/pichill/post/model/PostDAOImpl.java, src/main/java/com/pichill/post/service/PostService.java, src/main/java/com/pichill/post/service/PostServiceImpl.java, src/main/webapp/post/listAll.html
=> 頁數、上傳圖片、編輯文章、增加一些搜尋方法

src/main/java/com/pichill/generaluser/entity/GeneralUser.java, src/main/java/com/pichill/generaluser/model/GeneralUserDAO.java, src/main/java/com/pichill/generaluser/model/GeneralUserDAOImpl.java, src/main/java/com/pichill/reserveorder/entity/ReserveOrder.java, src/main/java/com/pichill/reserveorder/entity/TestReserveOrder.java, src/main/java/com/pichill/reserveorder/model/ReserveOrderDAO.java, src/main/java/com/pichill/reserveorder/model/ReserveOrderDAOImpl.java, src/main/java/com/pichill/reserveorder/service/ReserveOrderService.java, src/main/java/com/pichill/time/Time.java, src/main/webapp/generaluser/css2/allOrder.css, src/main/webapp/generaluser/guserListOne.jsp, src/main/webapp/reserveorder/listOneOrder.jsp, src/main/webapp/reserveorder/reserveOrder.jsp, src/main/webapp/reserveorder/reserveOrderList.jsp
更新: generaluser, reserveorder, time
=> 更新: generaluser,reserveorder,time

src/main/java/com/pichill/reserveorder/entity/ReserveOrder.java
=> 更新: reserveorder

src/main/java/com/pichill/reserveorder/entity/ReserveOrder.java
=> 更新:reserveorder

src/main/java/com/pichill/reserveorder/entity/ReserveOrder.java, src/main/java/com/pichill/time/TimeRef.java
=> 更新:ReserveOrder,TimeRef的VO

src/main/java/com/pichill/court/Court.java, src/main/java/com/pichill/court/CourtService.java, src/main/java/com/pichill/court/CourtServlet.java, src/main/java/com/pichill/owneruser/controller/OwnerUserServlet.java, src/main/java/com/pichill/owneruser/entity/OwnerUser.java, src/main/java/com/pichill/ownerusernotify/OwnerUserNnotifyDAO.java, src/main/java/com/pichill/place/Place.java, src/main/webapp/court/all_court.jsp, src/main/webapp/owneruser/ouserListOne.jsp, src/main/webapp/owneruser/owneruser.jsp
=> 企業會員、場館、場地更新

src/main/webapp/court/all_court.jsp, src/main/webapp/court/court.jsp, src/main/webapp/court/new_court.jsp, src/main/webapp/court/set_court.jsp, src/main/webapp/homepage/owneruserhome.jsp, src/main/webapp/owneruser/ouserListOne.jsp, src/main/webapp/owneruser/set_owneruser.jsp, src/main/webapp/place/new_place.jsp
=> 新增footer上的連結

src/main/java/com/pichill/frontstage/owneruser/controller/oUserAssoController.java, src/main/webapp/WEB-INF/web.xml, src/main/webapp/ginquirycourt/all_courtinfo.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000001.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000002.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000003.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000004.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000005.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000006.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000007.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000008.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000009.jsp, src/main/webapp/ginquirycourt/listOneCourt=61000010.jsp, src/main/webapp/homepage/disclaimer/odisclaimer.jsp, src/main/webapp/homepage/owneruserhome.jsp, src/main/webapp/homepage/privacyPolicy/oprivacyPolicy.jsp, src/main/webapp/homepage/termOfUse/otermOfUse.jsp, src/main/webapp/ownerusernotify/notify.jsp, src/main/webapp/testCourt/all_court.jsp, src/main/webapp/testCourt/new_court.jsp, src/main/webapp/testCourt/new_place.jsp, src/main/webapp/testCourt/set_court.jsp, src/main/webapp/testoUser/ouserlistOne.jsp, src/main/webapp/testoUser/owneruser.jsp
修正header、aside、footer連結，新增企業會員版本之"使用者條款"."隱私權政策"."免責條款"
=> 修正header、aside、footer連結，新增企業會員版本之"使用者條款"."隱私權政策"."免責條款"

src/main/webapp/homepage/privacyPolicy/oprivacyPolicy.jsp
=> 更改企業會員隱私權政策頁面
